resources:
- repo: self
queue:
  name: Hosted macOS
steps:
- task: NodeTool@0
  inputs:
    versionSpec: 10.x
    checkLatest: true
- task: Npm@1
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test:posix'
